version: '3.8'

services:
#  user-notification:
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./src:/app/src
#    depends_on:
#      - notification-service


  notification-service:
    image: aryekog/backend-interview-notifications-service:0.0.2
    ports:
      - "5001:5001"
    environment:
      - EMAIL_RATE_LIMIT=1
      - SMS_RATE_LIMIT=1
      - RATE_LIMIT_WINDOW_MS=1000
      - ERROR_RATE=0.1 
